import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

// Read API ID from file generated by deploy script
function getApiId() {
  try {
    const apiIdPath = path.resolve(__dirname, '.api-id')
    if (fs.existsSync(apiIdPath)) {
      return fs.readFileSync(apiIdPath, 'utf-8').trim()
    }
  } catch (e) {
    console.warn('Could not read API ID, using default proxy')
  }
  return 'todoapi' // fallback
}

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:4566',
        changeOrigin: true,
        rewrite: (path) => {
          const apiId = getApiId()
          return path.replace(/^\/api/, `/restapis/${apiId}/local/_user_request_`)
        }
      }
    }
  },
  build: {
    outDir: 'dist'
  }
})
